export default [
  {
    title: "Dune: Part Two",
    year: 2024,
    runtime: 166,
    genres: ["Sci-Fi", "Action", "Adventure"],
    imdb: { rating: 8.5 },
    plot: "Paul Atreides unites with the Fremen to wage war against House Harkonnen, while grappling with the visions of a devastating future his rise to power may bring.",
  },
  {
    title: "Wicked",
    year: 2024,
    runtime: 160,
    genres: ["Fantasy", "Musical", "Romance"],
    imdb: { rating: 7.7 },
    plot: "The untold story of the witches of Oz, following the unlikely friendship between a green-skinned outcast and a popular blonde before one becomes the Wicked Witch of the West.",
  },
  {
    title: "Top Gun: Maverick",
    year: 2022,
    runtime: 130,
    genres: ["Action", "Drama"],
    imdb: { rating: 8.2 },
    plot: "After decades of service, Pete Mitchell is called back to train a new generation of pilots for a dangerous mission, confronting ghosts from his past along the way.",
  },
  {
    title: "Inside Out 2",
    year: 2024,
    runtime: 96,
    genres: ["Animation", "Comedy", "Family"],
    imdb: { rating: 7.6 },
    plot: "As Riley enters adolescence, new emotions arrive to shake up her carefully balanced inner world, throwing Joy and the others into chaos.",
  },
  {
    title: "Deadpool & Wolverine",
    year: 2024,
    runtime: 128,
    genres: ["Action", "Comedy", "Sci-Fi"],
    imdb: { rating: 7.6 },
    plot: "A retired Deadpool is recruited by the TVA to team up with a reluctant Wolverine, crossing timelines to save his own universe from extinction.",
  },
  {
    title: "Sinners",
    year: 2025,
    runtime: 137,
    genres: ["Horror", "Drama"],
    imdb: { rating: 8.0 },
    plot: "Twin brothers return to their Mississippi hometown to start anew, only to discover an ancient evil waiting for them alongside the dangers they thought they'd left behind.",
  },
  {
    title: "28 Years Later",
    year: 2025,
    runtime: 115,
    genres: ["Horror", "Drama"],
    imdb: { rating: 7.0 },
    plot: "Decades after the rage virus escaped a lab, a small island community remains isolated from the infected mainland, until one man ventures back into the wasteland.",
  },
  {
    title: "A Minecraft Movie",
    year: 2025,
    runtime: 101,
    genres: ["Family", "Fantasy", "Comedy"],
    imdb: { rating: 6.0 },
    plot: "Four misfits are pulled through a portal into a cubic wonderland, where they must master creativity to survive and find a way home.",
  },
  {
    title: "Anora",
    year: 2024,
    runtime: 139,
    genres: ["Comedy", "Drama"],
    imdb: { rating: 7.6 },
    plot: "A young sex worker from Brooklyn gets her chance at a Cinderella story when she impulsively marries the son of a Russian oligarch, until his family intervenes.",
  },
  {
    title: "The Brutalist",
    year: 2024,
    runtime: 215,
    genres: ["Drama"],
    imdb: { rating: 8.0 },
    plot: "A visionary architect flees post-war Europe for America, where his life is forever changed by a wealthy, demanding client.",
  },
  {
    title: "Nickel Boys",
    year: 2024,
    runtime: 140,
    genres: ["Drama"],
    imdb: { rating: 7.6 },
    plot: "A powerful friendship develops between two young Black men as they navigate the harrowing trials of a segregation-era reform school together.",
  },
  {
    title: "Challengers",
    year: 2024,
    runtime: 131,
    genres: ["Drama", "Romance", "Sport"],
    imdb: { rating: 7.2 },
    plot: "A former tennis prodigy turned coach pushes her husband into a fierce rivalry with his former best friend, unearthing an old love triangle along the way.",
  },
  {
    title: "I Saw the TV Glow",
    year: 2024,
    runtime: 100,
    genres: ["Horror", "Drama"],
    imdb: { rating: 6.5 },
    plot: "Two teenagers bond over a mysterious late-night TV show, and one begins to suspect that the show's supernatural world may be more real than their own life.",
  },
  {
    title: "The Substance",
    year: 2024,
    runtime: 141,
    genres: ["Horror", "Drama"],
    imdb: { rating: 7.3 },
    plot: "A fading celebrity takes a black-market drug that creates a younger, better version of herself, with grotesque and escalating consequences.",
  },
  {
    title: "Past Lives",
    year: 2023,
    runtime: 105,
    genres: ["Drama", "Romance"],
    imdb: { rating: 7.9 },
    plot: "Childhood sweethearts reconnect decades after being separated, forced to confront questions of fate, connection, and the life not chosen.",
  },
  {
    title: "Poor Things",
    year: 2023,
    runtime: 141,
    genres: ["Comedy", "Drama", "Sci-Fi"],
    imdb: { rating: 7.9 },
    plot: "A young woman is brought back to life by an unorthodox scientist, embarking on a whirlwind adventure that awakens her to the strangeness of the world.",
  },
  {
    title: "The Zone of Interest",
    year: 2023,
    runtime: 105,
    genres: ["Drama", "History"],
    imdb: { rating: 7.4 },
    plot: "The commandant of Auschwitz and his family strive to build an idyllic life for themselves, right next door to the horrors within the camp walls.",
  },
  {
    title: "Glass Onion: A Knives Out Mystery",
    year: 2022,
    runtime: 139,
    genres: ["Comedy", "Mystery", "Crime"],
    imdb: { rating: 7.1 },
    plot: "Detective Benoit Blanc travels to a Greek island to investigate a murder among a group of wealthy friends during a puzzle-filled retreat, available on Netflix.",
  },
  {
    title: "Wake Up Dead Man: A Knives Out Mystery",
    year: 2025,
    runtime: 145,
    genres: ["Comedy", "Mystery", "Crime"],
    imdb: { rating: 7.0 },
    plot: "Benoit Blanc returns to unravel a new twisted case with an all-star cast of suspects, available on Netflix.",
  },
  {
    title: "The Thursday Murder Club",
    year: 2025,
    runtime: 110,
    genres: ["Comedy", "Mystery"],
    imdb: { rating: 6.6 },
    plot: "A group of retirees in a British retirement community who meet weekly to solve cold cases find themselves investigating a real murder close to home, available on Netflix.",
  },
  {
    title: "See How They Run",
    year: 2022,
    runtime: 98,
    genres: ["Comedy", "Mystery", "Crime"],
    imdb: { rating: 6.5 },
    plot: "In 1950s London, the murder of a Hollywood director on the set of a stage adaptation sends a world-weary inspector and an eager rookie down a trail of eccentric suspects.",
  },
  {
    title: "A Haunting in Venice",
    year: 2023,
    runtime: 103,
    genres: ["Mystery", "Thriller"],
    imdb: { rating: 6.5 },
    plot: "Retired detective Hercule Poirot attends a séance in a haunted Venetian palazzo that turns deadly, forcing him back into the world of murder investigation.",
  },
  {
    title: "Enola Holmes 2",
    year: 2022,
    runtime: 130,
    genres: ["Mystery", "Adventure", "Comedy"],
    imdb: { rating: 6.7 },
    plot: "Sherlock Holmes' younger sister opens her own detective agency and takes on her first official case, a missing girl tangled up in a much larger conspiracy, available on Netflix.",
  },
  {
    title: "The Residence",
    year: 2025,
    runtime: 55,
    genres: ["Comedy", "Mystery", "Crime"],
    imdb: { rating: 7.5 },
    plot: "When a beloved White House staffer is found dead during a state dinner, an eccentric detective must untangle a web of suspects among the staff and guests, available on Netflix.",
  },
  {
    title: "Lost Girls",
    year: 2020,
    runtime: 95,
    genres: ["Drama", "Mystery", "Crime"],
    imdb: { rating: 6.5 },
    plot: "A mother's search for her missing daughter uncovers a string of unsolved murders on Long Island, available on Netflix.",
  },
  {
    title: "The Woman in Cabin 10",
    year: 2025,
    runtime: 100,
    genres: ["Mystery", "Thriller"],
    imdb: { rating: 6.0 },
    plot: "A travel journalist aboard a luxury yacht witnesses a woman thrown overboard, but by morning every passenger is accounted for, and no one believes her, available on Netflix.",
  },
  {
    title: "All We Imagine as Light",
    year: 2024,
    runtime: 118,
    genres: ["Drama"],
    imdb: { rating: 7.5 },
    plot: "Two nurses navigate friendship, longing, and the challenges of womanhood while living and working in the sprawling city of Mumbai.",
  },
  {
    title: "Hundreds of Beavers",
    year: 2024,
    runtime: 108,
    genres: ["Comedy", "Adventure"],
    imdb: { rating: 7.5 },
    plot: "A 19th-century applejack salesman turned fur trapper wages an increasingly absurd, slapstick war against an army of cunning beavers to survive the winter.",
  },
  {
    title: "One Battle After Another",
    year: 2025,
    runtime: 162,
    genres: ["Action", "Drama", "Comedy"],
    imdb: { rating: 8.0 },
    plot: "A former revolutionary is pulled back into a world of chaos when a figure from his past resurfaces, forcing him to protect his daughter at any cost.",
  },
  {
    title: "Nosferatu",
    year: 2024,
    runtime: 132,
    genres: ["Horror", "Fantasy"],
    imdb: { rating: 7.3 },
    plot: "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, unleashing untold horror.",
  },
];
